<template><UiPanel :class="$style.component"><h2>Destinations</h2><UiStatePanel v-if="isPending" title="Loading destinations" icon="tabler:loader-2" live>Checking saved destinations…</UiStatePanel><UiStatePanel v-else-if="destinations.error" title="Could not load destinations" icon="tabler:alert-triangle">Try reloading this page.</UiStatePanel><UiStatePanel v-else-if="hasDestinations === false" title="No destinations yet" icon="tabler:send">Add a verified Telegram channel using the form.</UiStatePanel><ul v-else :class="$style.list"><li v-for="destination in destinations.data" :key="destination.id"><div><strong>Telegram</strong><span>Destination #{{ destination.id }}</span></div><UiStatusBadge :tone="destination.isActive ? 'success' : 'neutral'">{{ destination.isActive ? 'Active' : 'Inactive' }}</UiStatusBadge></li></ul></UiPanel></template>
<script setup lang="ts">
  import { getByNotificationId } from '~/composables/queries/notification/destinations'; import UiPanel from '~/components/ui/UiPanel.vue'; import UiStatePanel from '~/components/ui/UiStatePanel.vue'; import UiStatusBadge from '~/components/ui/UiStatusBadge.vue'; import { useQuery } from '@pinia/colada'; import { computed } from 'vue'

  interface Props { notificationId: number } const { notificationId } = defineProps<Props>(); const { state: destinations, isPending } = useQuery(() => getByNotificationId(notificationId)); const hasDestinations = computed(() => (destinations.value.data?.length ?? 0) > 0)
</script>
<style module>
  .component { display: grid; gap: var(--space-md); }
  .list { display: grid; gap: var(--space-sm); margin: 0; padding: 0; list-style: none; & li { display: flex; justify-content: space-between; align-items: center; gap: var(--space-md); padding: var(--space-md); border: var(--outline); border-radius: var(--radius-inner); background: var(--color-surface-muted); } & strong, & span { display: block; } & span { color: var(--color-ink-muted); font: 500 var(--text-metadata)/1.4 var(--font-metadata); } }
</style>
