packages:
  - apps/pepega
  - common/database
  - common/telegram
  - common/twitch
  - common/utils
  - workers/*

catalog:
  drizzle-orm: 0.44.7
  ofetch: 1.5.1
  typescript: 5.9.3
  valibot: 1.1.0
  wrangler: 4.49.1

cleanupUnusedCatalogs: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild

saveExact: true
