packages:
  - apps/pepega
  - common/database
  - common/twitch
  - common/utils
  - workers/*

catalog:
  drizzle-orm: 0.40.0
  wrangler: 3.114.1
  typescript: 5.8.2

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
  - workerd

# .npmrc
# Something wrong with pnpm and Nuxt build without this
nodeLinker: hoisted
