packages:
  - apps/pepega
  - common/database
  - common/telegram
  - common/twitch
  - common/utils
  - workers/*

catalog:
  drizzle-orm: 0.44.2
  wrangler: 4.24.3
  typescript: 5.8.3
  ofetch: 1.4.1
  valibot: 1.1.0

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild

saveExact: true
