packages:
  - apps/pepega
  - common/database
  - common/twitch
  - common/utils
  - workers/*
catalog:
  drizzle-orm: 0.42.0
  wrangler: 4.11.0
  typescript: 5.8.3

nodeLinker: hoisted
saveExact: true

onlyBuiltDependencies:
  - esbuild
