packages:
  - apps/pepega
  - common/database
  - common/telegram
  - common/twitch
  - common/utils
  - workers/*

catalog:
  drizzle-orm: 0.44.3
  ofetch: 1.4.1
  typescript: 5.8.3
  valibot: 1.1.0
  wrangler: 4.26.0

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild

saveExact: true
