packages:
  - apps/pepega
  - common/database
  - common/telegram
  - common/twitch
  - common/utils
  - workers/*

allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  sharp: false
  vue-demi: false
  workerd: false

catalog:
  drizzle-orm: 1.0.0-rc.5-169397b
  ofetch: 1.5.1
  tsx: 4.23.12
  typescript: 7.0.2
  valibot: 1.4.2
  wrangler: 4.123.0

cleanupUnusedCatalogs: true

nodeLinker: hoisted

saveExact: true
