packages:
  - apps/pepega
  - common/database
  - common/twitch
  - common/utils
  - workers/*
catalog:
  drizzle-orm: 0.44.2
  wrangler: 4.19.1
  typescript: 5.8.3

nodeLinker: hoisted
saveExact: true

onlyBuiltDependencies:
  - esbuild
