packages:
  - apps/pepega
  - common/database
  - common/twitch
  - common/utils
  - workers/*
catalog:
  drizzle-orm: 0.40.0
  wrangler: 4.0.0
  typescript: 5.8.2

nodeLinker: hoisted
saveExact: true

onlyBuiltDependencies:
  - esbuild
