packages:
  - apps/pepega
  - common/database
  - common/telegram
  - common/twitch
  - common/utils
  - workers/*

catalog:
  drizzle-orm: 0.45.1
  ofetch: 1.5.1
  tsx: 4.21.0
  typescript: 5.9.3
  valibot: 1.2.0
  wrangler: 4.58.0

cleanupUnusedCatalogs: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild

saveExact: true
