packages:
  - apps/pepega
  - common/database
  - common/telegram
  - common/twitch
  - common/utils
  - workers/*

catalog:
  drizzle-orm: 0.44.5
  ofetch: 1.4.1
  typescript: 5.9.2
  valibot: 1.1.0
  wrangler: 4.33.2

cleanupUnusedCatalogs: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild

saveExact: true
