packages:
  - apps/pepega
  - common/database
  - common/twitch
  - common/utils
  - workers/*

catalog:
  drizzle-orm: 0.40.1
  wrangler: 4.2.0
  typescript: 5.8.2

# .npmrc
# Something wrong with pnpm and Nuxt build without this
nodeLinker: hoisted
