export type ButtonVariant = 'primary' | 'secondary' | 'danger' | 'twitch' | 'ghost'
export type PanelVariant = 'quiet' | 'standard' | 'featured'
export type StatusTone = 'neutral' | 'success' | 'warning' | 'danger' | 'info'
export type ThemePreference = 'system' | 'light' | 'dark'
export type ToastTone = 'info' | 'success' | 'error'
