<template><UiPanel :class="$style.component"><header :class="$style.header"><div><h2>Telegram channels</h2><p>Verified channels can receive Twitch live alerts.</p></div><UiButton icon="tabler:plus" @click="isAddOpen = true">Add channel</UiButton></header><UiStatePanel v-if="isPending" title="Loading channels" icon="tabler:loader-2" live>Checking your Telegram channels…</UiStatePanel><UiStatePanel v-else-if="channels.error" title="Could not load channels" icon="tabler:alert-triangle">Reload the page to try again.</UiStatePanel><UiStatePanel v-else-if="channelList.length === 0" title="No Telegram channels" icon="tabler:brand-telegram">Add a channel and verify it with the Pepega bot.</UiStatePanel><ul v-else :class="$style.list"><li v-for="channel in channelList" :key="channel.id"><div :class="$style.channel"><strong>@{{ channel.chatId }}</strong><span>Channel ID {{ channel.id }}</span></div><UiStatusBadge :tone="channel.isVerified ? 'success' : 'warning'">{{ channel.isVerified ? 'Verified' : 'Pending' }}</UiStatusBadge><DropdownMenuRoot><DropdownMenuTrigger as-child><UiIconButton icon="tabler:dots" :label="`Actions for @${channel.chatId}`" /></DropdownMenuTrigger><DropdownMenuPortal><DropdownMenuContent :class="$style.menu" :side-offset="8" align="end"><DropdownMenuItem v-if="channel.isVerified === false" :class="$style.menuItem" @select="openVerification(channel)"><Icon name="tabler:circle-check" aria-hidden="true" />Verify channel</DropdownMenuItem><DropdownMenuItem :class="[$style.menuItem, 'danger']" @select="openDelete(channel)"><Icon name="tabler:trash" aria-hidden="true" />Delete channel</DropdownMenuItem></DropdownMenuContent></DropdownMenuPortal></DropdownMenuRoot></li></ul><UiDialog v-model="isAddOpen" title="Add Telegram channel" description="Enter the public channel name without @."><form :class="$style.form" @submit.prevent="addChannel"><UiField label="Channel name" for-id="telegram-chat-id" helper="Example: perdTV" :error="addError"><UiTextInput id="telegram-chat-id" v-model="newChatId" minlength="5" maxlength="32" autocomplete="off" /></UiField><UiButton type="submit" :disabled="isAddDisabled">{{ isAddingChannel ? 'Adding…' : 'Add channel' }}</UiButton></form></UiDialog><VerificationDialog v-if="verificationChannel" v-model="isVerifyOpen" :chat-id="verificationChannel.chatId" :channel-id="verificationChannel.id" /><UiConfirmDialog v-model="isDeleteOpen" :title="deleteTitle" confirm-label="Delete channel" @confirm="deleteChannel">This removes the channel from Pepega and from any destinations that use it.</UiConfirmDialog></UiPanel></template>
<script setup lang="ts">
  import type { TelegramChannelModel } from '~~/shared/models/telegram-channels'; import { getTelegramChannels } from '~/composables/queries/telegram/channels'; import { useAddTelegramChannel } from '~/composables/mutations/telegram/add-channel'; import { useDeleteTelegramChannel } from '~/composables/mutations/telegram/delete-channel'; import VerificationDialog from './telegram/VerificationDialog.vue'
  import UiButton from '~/components/ui/UiButton.vue'; import UiConfirmDialog from '~/components/ui/UiConfirmDialog.vue'; import UiDialog from '~/components/ui/UiDialog.vue'; import UiField from '~/components/ui/UiField.vue'; import UiIconButton from '~/components/ui/UiIconButton.vue'; import UiPanel from '~/components/ui/UiPanel.vue'; import UiStatePanel from '~/components/ui/UiStatePanel.vue'; import UiStatusBadge from '~/components/ui/UiStatusBadge.vue'; import UiTextInput from '~/components/ui/UiTextInput.vue'
  import { DropdownMenuContent, DropdownMenuItem, DropdownMenuPortal, DropdownMenuRoot, DropdownMenuTrigger } from 'reka-ui'; import { useQuery } from '@pinia/colada'; import { computed, ref } from 'vue'

  const { state: channels, isPending } = useQuery(getTelegramChannels); const { mutateAsync: addChannelMutation, isLoading: isAddingChannel } = useAddTelegramChannel(); const { mutateAsync: deleteChannelMutation } = useDeleteTelegramChannel(); const isAddOpen = ref(false); const isVerifyOpen = ref(false); const isDeleteOpen = ref(false); const newChatId = ref(''); const addError = ref(''); const verificationChannel = ref<TelegramChannelModel | null>(null); const deletionChannel = ref<TelegramChannelModel | null>(null)
  const channelList = computed(() => channels.value.data ?? []); const isAddDisabled = computed(() => newChatId.value.length < 5 || isAddingChannel.value); const deleteTitle = computed(() => deletionChannel.value === null ? 'Delete channel?' : `Delete @${deletionChannel.value.chatId}?`)
  async function addChannel() { addError.value = ''; try { await addChannelMutation(newChatId.value); newChatId.value = ''; isAddOpen.value = false } catch (error) { console.error('Failed to add Telegram channel', error); addError.value = 'The channel could not be added. Check the name and try again.' } }
  function openVerification(channel: TelegramChannelModel) { verificationChannel.value = channel; isVerifyOpen.value = true }
  function openDelete(channel: TelegramChannelModel) { deletionChannel.value = channel; isDeleteOpen.value = true }
  async function deleteChannel() { if (deletionChannel.value === null) {return;} const channelId = deletionChannel.value.id; try { await deleteChannelMutation(channelId); deletionChannel.value = null } catch (error) { console.error('Failed to delete Telegram channel', error) } }
</script>
<style module>
  .component { display: grid; gap: var(--space-lg); }
  .header { display: flex; justify-content: space-between; align-items: start; gap: var(--space-md); flex-wrap: wrap; & h2 { font-size: 1.5rem; } & p { color: var(--color-ink-secondary); } }
  .list { display: grid; gap: var(--space-sm); margin: 0; padding: 0; list-style: none; & > li { display: grid; grid-template-columns: minmax(0, 1fr) auto auto; align-items: center; gap: var(--space-sm); padding: var(--space-sm); border: var(--outline); border-radius: var(--radius-inner); background: var(--color-surface-muted); } }
  .channel { min-inline-size: 0; & strong, & span { display: block; overflow: hidden; text-overflow: ellipsis; } & span { color: var(--color-ink-muted); font: 500 var(--text-metadata)/1.4 var(--font-metadata); } }
  .menu { z-index: 70; min-inline-size: 12rem; padding: var(--space-xs); border: var(--outline); border-radius: var(--radius-control); background: var(--color-surface); box-shadow: var(--shadow-card); }
  .menuItem { min-block-size: 2.5rem; display: flex; align-items: center; gap: var(--space-xs); padding: 0 var(--space-sm); border-radius: var(--radius-cell); outline: none; &[data-highlighted] { background: var(--color-surface-muted); } &:global(.danger) { color: var(--color-danger); } }
  .form { display: grid; gap: var(--space-lg); & > button { justify-self: end; } }
  @media (max-width: 30rem) { .list > li { grid-template-columns: minmax(0, 1fr) auto; } .list > li > span { grid-row: 2; justify-self: start; } }
</style>
