name: Database migration (staging)

on:
  pull_request:
    branches:
      - master
    paths:
<<<<<<< Updated upstream
      - 'migrations/**'
=======
      - 'common/database/migrations/**'
>>>>>>> Stashed changes

jobs:
  migration:
    runs-on: ubuntu-24.04
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'
      - name: Install dependencies
        run: npm --workspace @pepega/database ci
      - name: Run database migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
<<<<<<< Updated upstream
        run: npm run db:migrate
=======
        run: npm --workspace @pepega/database run db:migrate
>>>>>>> Stashed changes
      - name: Seed database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm --workspace @pepega/database run db:seed
