name: Deploy Twitch webhooks

permissions:
  contents: read

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/deploy-twitch-webhooks.yml
      - workers/twitch-webhooks/**
      - common/database/**
      - common/twitch/**
      - common/utils/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/deploy-twitch-webhooks.yml
      - workers/twitch-webhooks/**
      - common/database/**
      - common/twitch/**
      - common/utils/**

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: ${{ github.event_name == 'push' && 'production' || 'staging' }}
    steps:
      - uses: Perdolique/automations/.github/actions/setup-pnpm@v3
        with:
          install-dependencies: 'true'
      - name: Typecheck monorepo
        run: pnpm run test:typecheck
      - name: Validate Worker bundle
        run: pnpm --filter @pepega/twitch-webhooks run deploy:dry-run
      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: pnpm --filter @pepega/twitch-webhooks run deploy:${{ github.event_name == 'push' && 'production' || 'staging' }}
